[project]
name = "rpi-cat-behaviour-monitoring"
version = "0.1.0"
description = "Raspberry Pi app to monitor cats with live video feed and identify poor behaviour"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "black[jupyter]==25.12.0",
    "ipykernel>=7.1.0",
    "isort==7.0.0",
    "mypy==1.19.1",
    "pre-commit==4.5.0",
    "pycocotools>=2.0.11",
    "ultralytics>=8.3.239",
]

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
strict_optional = false
files = '.'